// 自动生成：tools_s243/gen_art.py（S243 AI 生成美术 → 16×16 字符画）。改图：改下面的字符画，或把同名 PNG 放进 Assets/Resources/Step1Art/<Key>.png 覆盖。
using System.Collections.Generic;

/// <summary>
/// S243：用户「图示是不是都生成了直观美术？场景、马里奥、捣蛋者能不能更直观」——之前只有 16×16 程序画的图标，角色和地形还是红蓝方块。
/// 这里是 GPT Image 2 生成的原创像素素材（洋红底图 → 切格 → 缩到 16×16 → 吸到项目调色板 → 自动补深色描边），全部过 OverworldArt.Audit。
/// 角色：寻宝人（红帽，马里奥位）5 帧 = 站 / 跑 A / 跑 B / 跳 / 晕；小恶魔（蓝，捣蛋者）5 帧 = 站 / 踮脚 A / 踮脚 B / 跳 / 变身烟。
/// 机关 22 个 + 徽章 8 个替换 Step1Icons 里程序画的旧图（Step1Icons.Pixels 先查这里）；地形 6 块；背景 64×36 低对比（主层黑描边、背景无描边、中间明度）。
/// 参考：主层实心深描边 + 背景低对比无描边 https://www.sandromaglione.com/articles/pixel-art-platformer-level-design-full-guide ；
/// 16×16 角色大头（头约占 45%）、先剪影 https://spritegen.io/guides/how-to-draw-a-pixel-art-character/ ；障碍和背景要拉开明度 https://www.reddit.com/r/gamedev/comments/w5w6xd/ 。
/// 只换外观：碰撞体、判定框、玩法一律不动（H3）。
/// </summary>
public static class Step1Art
{
    public const int Size = 16;
    /// <summary>S243 补的 4 个颜色（皮肤亮 / 皮肤暗 / 深蓝裤子 / 暗灰）——OverworldArt.Palette 没有的才放这里。</summary>
    public static readonly Dictionary<char, float[]> ExtraPalette = new Dictionary<char, float[]>
    {
        { 'f', new[] { 0.98f, 0.78f, 0.6f } },
        { 'F', new[] { 0.78f, 0.52f, 0.38f } },
        { 'd', new[] { 0.14f, 0.2f, 0.42f } },
        { 'e', new[] { 0.25f, 0.25f, 0.3f } },
    };
    public static readonly Dictionary<string, string[]> Icons = new Dictionary<string, string[]>
    {
        { "FireTrap", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "ekk.............",
            "kSSeN.kkkkkk....",
            "kSssNkooooorkk..",
            "ksssSfwfwfooork.",
            "eSSSNyffwfoork..",
            "eeeSekkrooork...",
            "eeeee..kkkkk....",
            "kkk.............",
        } },
        { "ControllableBlocker", new[] {
            "................",
            "....SSSSSSSe....",
            "....eSSSSSSe....",
            "....xSSRRRSx....",
            "....xwFrrFfx....",
            "....xFrrFwfk....",
            "....xrrFwwrk....",
            "....xrFwwrRx....",
            "....xFwwrrRx....",
            "....xwwFrrsx....",
            "....xwFrrffx....",
            "....xFrrfwsk....",
            "....xrrfwfRx....",
            "....xRNSSNRx....",
            "....Ssssssse....",
            "....eeeeeeee....",
        } },
        { "CollapsingPlatform", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            ".N...........N..",
            "eN...........Ne.",
            "kNNn.......nNNk.",
            "NN.NNn...NNN.Nk.",
            "NN..Nk.N.kN..Nk.",
            "kNkNNk...kNNkNk.",
            "NNNnNN...NNnNNN.",
            "NnNnnN...NnnNnN.",
            "NNNNNNN..NNNNNN.",
            "kkkkkk.N.kkkkkk.",
        } },
        { "SpringPad", new[] {
            "................",
            "................",
            "eeeeeeeeeeeeeee.",
            "eggggggggggggge.",
            "kGGGGGGGGGGGGGk.",
            "kkkkkkkkkkkkkkk.",
            "..eSSSSSSSsSk...",
            "..effsSeekkk....",
            "...keeeSswsek...",
            "..eSSSSSssfsk...",
            "..esfsSeekkk....",
            "...xeeeSsfFek...",
            ".eksssSSsssskek.",
            "kGGeeeeeeeeeGGk.",
            "eggggggggggggge.",
            "kkkkkkkkkkkkkkk.",
        } },
        { "CrackFloor", new[] {
            "................",
            "................",
            ".eNNNNkkNNNNNNN.",
            ".NnnnnNknnnnnnk.",
            ".Nnnnnennnnnnnk.",
            ".NnnnNxnnnnnnnk.",
            ".kNnNNNNnnnnNNx.",
            ".NnNnnnNNnnNNne.",
            ".NnNnnnnkNNNnnk.",
            ".NnnnnnNknnnnnk.",
            ".Nnnnnnknnnnnnk.",
            ".knnnNkxNnnnnnk.",
            ".NnnnNNnkNnnnnk.",
            ".NnnnNnnnkNnnnk.",
            ".NnnNnnnnNennnk.",
            ".kkkkkkkkkxkkkk.",
        } },
        { "IronCage", new[] {
            "................",
            "......kek.......",
            "......kke.......",
            ".......k........",
            "......kke.......",
            "......eee.......",
            "....ekSkeke.....",
            "....kSSSSSk.....",
            "...ekkkkkkkk....",
            "...kekekkkee....",
            "...kekekkkee....",
            "...kkkekkkke....",
            "...kekekkkee....",
            "...kekekxkee....",
            "...kekekkkee....",
            "...eeeeeeeee....",
        } },
        { "SnareTrap", new[] {
            "................",
            ".......Ne.......",
            ".......NN.......",
            ".......NN.......",
            ".......Nk.......",
            ".......NNk......",
            ".......NNN......",
            "......NNkN......",
            ".....NN..NN.....",
            "....NN....NN....",
            "....NN....NN....",
            "....N.....eN....",
            "....NN....NN....",
            "....NN....NN....",
            ".....NN..NN.....",
            "......NNNN......",
        } },
        { "OilBarrel", new[] {
            "................",
            "...kRRRRRRRk....",
            "..RRRRRRRRRRR...",
            "..kNNnnnnnRRk...",
            "..krRRRRRRRRk...",
            "..krrFrrrrRRk...",
            "..RrrFrrrrRRk...",
            "..kRnnnnnnRRk...",
            "..krrffFfFRRk...",
            "..krrfrRFFRRk...",
            "..RrrFrorFRRR...",
            "..kRrfoooFRRk...",
            "..kRRnRRRRRRk...",
            "..krrrrrrrRRk...",
            "..RrrFrrrrRRR...",
            "...kNNNNNNRk....",
        } },
        { "Tripwire", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "eeN..........NeN",
            "kSkkkkkkkkkkkeSk",
            ".ek..........ke.",
            ".kk..........kk.",
            "kSk..........kSk",
            "eek..........eek",
        } },
        { "Vent", new[] {
            "................",
            ".....kkeee......",
            "...kksFSSSke....",
            "..ksFSSeSSSSe...",
            ".kseSexxkeSeSe..",
            ".kSSkkkxexkSSe..",
            "ksSexkkxexkeSSk.",
            "kSSkkkexexekFSe.",
            "eSSkkkexexeksee.",
            "eSSkkkexexeksSe.",
            "eSSekkexexeesSk.",
            ".eSSxkexexksSe..",
            ".eSSSekxkeFSSe..",
            "..eSSSsssssSe...",
            "...ekSSeSSkk....",
            ".....eeeek......",
        } },
        { "CrackedWall", new[] {
            "................",
            "................",
            ".Nkkkxkkkekkkke.",
            ".kSSSesSSSsSSSe.",
            ".eSSSeSSSeSSSSe.",
            ".eSSeeeeekSSSSk.",
            ".kSSSsSSkSsSSFe.",
            ".eSSSSSSksSSSSe.",
            ".kSeSSSekSSSSek.",
            ".kssSSekeSSesse.",
            ".eSSSSSesSSSSSe.",
            ".eSSSSSkSSSSSSe.",
            ".eSSSeSekeSSSSk.",
            ".kSSSSFSeksSSSe.",
            ".eSSSSSSSkSSSSe.",
            ".eeekkeekkkeeek.",
        } },
        { "Bush", new[] {
            "................",
            "................",
            ".....kkGek......",
            "...eeGggGGke....",
            "..kggGgGgGGG....",
            ".SGGggGgggGGGk..",
            ".GggggGggGGGGk..",
            ".GGGGggGGGgGGek.",
            "egGGggGGGggGGek.",
            "kGgGggGGGGgGGGk.",
            "eGGGGGGggGGGGek.",
            "kGGGGGGGGGGGGG..",
            ".eGGGGGGGGGeee..",
            ".kGGGGGGGGGGek..",
            "..kGGeGeGGeGe...",
            "...kkkkkkkkk....",
        } },
        { "OneWayDoor", new[] {
            "................",
            "...xNNNNNNek....",
            "..xNnNNNNNnNk...",
            "..enNNNNNNNne...",
            "..kNNNNNNNNNe...",
            "..kNNNNNNNNNk...",
            "..kNNNNeNNNNk...",
            "..kNkNkYNNNNk...",
            "..kNNyyyYNNNk...",
            "..kNNYYyYNNNk...",
            "..kNNkknNNnNk...",
            "..kNNNNkNNnNk...",
            "..kNNNNNNNkNk...",
            "..kNNNNNNNNNk...",
            "..kNNNNNNNNNk...",
            "..kkkkkkkkkkk...",
        } },
        { "PoisonPool", new[] {
            "................",
            "................",
            "................",
            "................",
            ".........Nk.....",
            "........kwe.....",
            "....e....k......",
            "...k.k..........",
            "....kk.eke..k...",
            "......k..kx.ek..",
            "...kkkkkkekkk...",
            ".kkPPPkekePkPkk.",
            "kPPPPk.kPPk.kdk.",
            "kPPPPPkPPPPkPPk.",
            ".kkkkdPPPPeeekk.",
            ".....kkkkk......",
        } },
        { "Glue", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "....kNkkkN......",
            "..NkyyyyyykkkN..",
            "..NNYyyYoyyyyk..",
            "NknyyoYyyyyyNx..",
            "NkyyyyyyyYYyyykN",
            "..NknyyykyyyYNN.",
            "....NNNN.NNNN...",
        } },
        { "RoomLamp", new[] {
            "................",
            "........xek.....",
            "........xSk.....",
            ".......eSSSe....",
            "..k...kkeeekk...",
            ".kek.keSSSSeek..",
            ".kex..eSnSSSNx..",
            ".kekkkNwywfwn...",
            ".keeSSNwywfwn...",
            ".kekekNwywfwn...",
            ".kex..Nwywffn...",
            ".kex..Nfywffn...",
            ".Rk....nYsYYx...",
            "......kkeeekx...",
            ".......kkkkx....",
            "........kkk.....",
        } },
        { "SpikeTrap", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "..k...k..k...k..",
            "..k..ek..kk..ke.",
            ".kse.ksk.kk.esk.",
            ".ksSxsseesseSsk.",
            "keSexeekkeekkSex",
            "eSSSSSSSSSSSSSSe",
            "kkkkkkkkkkkkkkkk",
        } },
        { "Cannon", new[] {
            "................",
            "................",
            "................",
            "............ee..",
            "....kkkkkkkkeSe.",
            "..keeeeeeeeeekk.",
            ".keeeeeeeeeeexk.",
            ".keeeeeeeeeeexk.",
            ".keekkkkeeeeexk.",
            ".keeknNnkkkkekk.",
            "..kkkNknxkkkeSk.",
            ".NnnnnnnnnN.kk..",
            "NNNNNnnnNNN.....",
            "kNNNNnnNnNnk....",
            ".NNNkkkkNNN.....",
            "..ke....kke.....",
        } },
        { "PickupSpot", new[] {
            "................",
            "................",
            ".NNNNNNNNNNNNNN.",
            ".NYYyyyyyyyyYYN.",
            ".NYnoYNNNNYonYN.",
            ".NooYFwwwwSYooN.",
            ".NooSwsssswNooN.",
            ".NooSwSYnFwNooN.",
            ".NoonNnnSwfnooN.",
            ".NoooonfwfnYooN.",
            ".NooooNwfNYoooN.",
            ".NooooneeYooooN.",
            ".NooooNwfnooooN.",
            ".NYnoonssnooYYN.",
            ".NYnYYYnnYYYnYN.",
            ".NNNNNNNNNNNNNN.",
        } },
        { "Crate", new[] {
            "................",
            "................",
            ".keeeeeeeeeeeek.",
            ".ennnnnnnnnnnnk.",
            ".kNNNNNNNNNNNNk.",
            ".enNNNNNNNNNNNk.",
            ".enNNnnNNNnNNNk.",
            ".enNkNnNnnNkNNk.",
            ".enNNNNNnNNNNNk.",
            ".enNNNNnNNNNNNk.",
            ".enNNNnNNnNNNNk.",
            ".enNNnNNNNnNNNk.",
            ".kNNNNNNNNNNNNk.",
            ".kNNNNNNNNNNNNk.",
            ".knNNNNNNNNNNNk.",
            ".kkkkkkkkkkkkkx.",
        } },
        { "GrassGround", new[] {
            "................",
            "................",
            "................",
            ".NeeeeeeeeeeeeN.",
            ".egggggggggggge.",
            ".egggggggggggge.",
            ".kGgGGGgGGGGege.",
            ".kkGeeeGekeGkek.",
            ".kNkNNNkNNNkNNx.",
            ".knNNnnNNNNNnNk.",
            ".knNNnNNNNnNNNk.",
            ".kNnnNNNnNNNNNk.",
            ".kNNNNNnNNNnnNk.",
            ".knNNNnNNNNNNNk.",
            ".kNNNNNNNNNNNNk.",
            ".kxxkkkxxkkxxkk.",
        } },
        { "BananaPeel", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            ".....kk.........",
            ".....xNk........",
            "....NYyYN.......",
            "....NyyyN.......",
            "....Nyyyk.......",
            "....eyyyk.......",
            "....kyyyoN......",
            "...NyyYyyYkk....",
            ".kkyyYeyynYykke.",
            "eyykNk.kyyYxkk..",
            ".kx.....NNkN....",
        } },
        { "BadgeLoot", new[] {
            "................",
            ".xNkkkkkkkkkNx..",
            "xNYNNNNNNNNNYNx.",
            "eyfNnnnnnnnNYyN.",
            "NyYkNNNNNNNkYyN.",
            "NyYNnNNNNNNNYyN.",
            "NyYkkkssFekkYyN.",
            "NyonnYfeYYnnYyN.",
            "kNNNNnyNYnNNNNk.",
            "eYYkNkYYYNNknYN.",
            "NyYkNkkkkkNkYyN.",
            "NyYkNNNNNNNNYyN.",
            "NyYkkkkkkkkkYyN.",
            "NyyoooooooooyyN.",
            "kNNNNNNNNNNNNNk.",
            "................",
        } },
        { "BadgeExit", new[] {
            "................",
            "keeeeeeeek......",
            "eeeeeeeeSk......",
            "eeGGGGGGek......",
            "eeGGGGGGek......",
            "eeGGGGGGek.ek...",
            "eeGGGGGGkkxsSe..",
            "eeGGGGGGSffwwSx.",
            "eeGGGGSeSwwwwwS.",
            "eeGGGGeeSwwwwSk.",
            "eeGGGGGGkkxsse..",
            "eeGGGGGGek.Sx...",
            "eeGGGGGGek......",
            "eeGGGGGGek......",
            "kkkkkkkkkk......",
            "................",
        } },
        { "BadgeQuestion", new[] {
            "....xNNNNNNx....",
            "..kNYyyyyyyYNk..",
            "..NyyYNSSNnyyN..",
            ".kYyYSwwwwSnyYk.",
            ".NyynffSSfwNyyN.",
            ".NyyYnnYnswNyyN.",
            ".NyyyyynswsnyyN.",
            ".NyyyynswSnyyyN.",
            ".NyyyynssnyyyyN.",
            ".eYyyyYnnYyyyYe.",
            ".knyyynSSnyyyYk.",
            "..kYyynSSnyyYk..",
            "...kNYyyyyyNk...",
            ".....xxnYxk.....",
            ".......kk.......",
            "................",
        } },
        { "BadgeAlert", new[] {
            "....xkkkkkkx....",
            "...kRrrrrrrRRk..",
            "..krrrkNNerrrR..",
            ".kRrrrSwwSrrrRk.",
            ".RrrrrSwwSrrrrk.",
            ".RrrrrSwwSrrrrk.",
            ".Rrrrrksferrrrk.",
            ".RrrrrRssRrrrrk.",
            ".RrrrrRSSRrrrrk.",
            ".krrrrrRRrrrrrk.",
            ".kRrrrRSsRrrrR..",
            "..xRrrReSRrrrx..",
            "...kRrrrrrrRk...",
            ".....xxRRxx.....",
            ".......kk.......",
            "................",
        } },
        { "BadgeEye", new[] {
            "................",
            "................",
            "................",
            "....kkkkkke.....",
            "..kkffeeesfkk...",
            ".kSwweBBBdfwsk..",
            "kswweBwSkBewwsx.",
            "kwwweBekxBdwwwk.",
            "xswweBkxkBdwwsx.",
            ".kSwfdBBBdswsk..",
            "..kkfseeesfkk...",
            "....kkkkkke.....",
            "................",
            "................",
            "................",
            "................",
        } },
        { "BadgeStar", new[] {
            ".......N........",
            ".......n........",
            "..NN..xnx..eN...",
            "..e...NyN...k...",
            ".....xYyYk......",
            "....kNyyynx.....",
            "..kNYyyyyyYNk...",
            "NnnyyyyyyyyyYnN.",
            "kkknyyyyyyynkkx.",
            "....eYyyyYN.....",
            ".....xyyyk......",
            "......NyN...k...",
            "..NN..kYk..kN...",
            ".......n........",
            ".......N........",
            "................",
        } },
        { "BadgeAmbush", new[] {
            "....kkRRRkk.....",
            "..kkRrrrrrRkk...",
            "..krFwwwwwFrk...",
            ".krfwfrrrfwfrk..",
            ".RFwFrFFFrFwFR..",
            "krffrFwwwFrffrk.",
            "RFwFFwfrfwrFwrR.",
            "RrwrFwrrrwFrwrR.",
            "RrwrFwfrfwFrwrR.",
            "krffrFwwwFrffrk.",
            "kRFwFrFFFrFwFR..",
            ".krfwfrrrfwfrk..",
            ".kkrFwwwwwFrkk..",
            "..kkRrrrrrRkk...",
            "....kkRRRkx.....",
            "................",
        } },
        { "BadgeHide", new[] {
            "................",
            "................",
            "....xk..........",
            "....dbdkBBk.k...",
            ".kkkdbBBbdkBd...",
            ".dSSkBBBBdbBk...",
            "..ebBdBddBbdBe..",
            ".xdBBdkkdBBBBB..",
            "kBbBddbbdBBBdx..",
            "kBSSdBBSddebSek.",
            "kdkddBBkkBBSdBd.",
            "kBBdBBdBddBdBBk.",
            "xkdddddddddddkk.",
            "................",
            "................",
            "................",
        } },
    };
    /// <summary>角色帧：Hero = 马里奥位（站 / 跑 A / 跑 B / 跳 / 晕），Imp = 捣蛋者（站 / 踮脚 A / 踮脚 B / 跳 / 变身烟）。</summary>
    public static readonly Dictionary<string, string[]> Frames = new Dictionary<string, string[]>
    {
        { "Hero0", new[] {
            "................",
            "................",
            "................",
            "................",
            "......RRRRR.....",
            ".....RrrrRRk....",
            "....RrrRkNNk....",
            "....RrReoFNk....",
            "...RRRNfSoS.....",
            "....kknfnfn.....",
            "....NkknFFF.....",
            "...NNkRNRk......",
            "...NNNRkRkN.....",
            "....kFNdekn.....",
            ".....kdddk......",
            ".....kNkke......",
        } },
        { "Hero1", new[] {
            "................",
            "................",
            "................",
            "................",
            ".......RRRRR....",
            "......RrrRRRk...",
            ".....RrrRNNNk...",
            ".....RRReYFNk...",
            "....RRRNYSoS....",
            ".....kkNfFfn....",
            "....nRRkNnnN....",
            "....fNRNrRkNn...",
            "....kNkkNNRR....",
            "...Nkdddkdd.....",
            "...kkdd..deN....",
            "..........NN....",
        } },
        { "Hero2", new[] {
            "................",
            "................",
            "................",
            "................",
            ".......RRRRR....",
            "......RrrrRRk...",
            ".....RrrRkNNk...",
            ".....RRReFFNk...",
            "....RRRNFSoN....",
            ".....kknoFfn....",
            "....NNkkNnnF....",
            "....NNkRrRnF....",
            "....kkkkRRnF....",
            "...Nedddddd.....",
            "...kkdd.ddeN....",
            "..........N.....",
        } },
        { "Hero3", new[] {
            "................",
            "................",
            "................",
            "......RRRRk.....",
            ".....RrrrRRk....",
            "....RrrRkNNe....",
            "....RRRkFFNk....",
            "...nnRNFSoSNn...",
            "...FnRnonfnNF...",
            "....kRRnFFnR....",
            "....kNRNRRR.....",
            "....NNkNNk......",
            "....Nkddddd.....",
            ".....ddd.kk.....",
            "....Nek..k......",
            "....NN..........",
        } },
        { "Hero4", new[] {
            "................",
            ".....k..........",
            ".....kk....kk...",
            "...........kk...",
            "......RkkR......",
            ".....RrRNrR.....",
            "....RrrRNNNk....",
            "....RrRenNkk....",
            "...RRRNnnFe.....",
            "....kRnnnnN.....",
            "....NkNoFFk.....",
            "...NNNRkRk......",
            "...NNRRNRkR.....",
            "....kfNkNek.....",
            ".....Ndddk......",
            "......ekkk......",
        } },
        { "Imp0", new[] {
            "................",
            "................",
            ".......d........",
            "......dk....d...",
            "......dbkkkdd...",
            "......kbbbbbk...",
            ".....kbbBSBbbe..",
            ".....kbbBwsBdk..",
            ".....kbbBfwesk..",
            ".....dBbBSSBSe..",
            "......dBBSsBk...",
            "..k..RPBbbbk....",
            ".dd.RRBbBbbBd...",
            ".kkkRreBBbbBd...",
            "...kRRkdBdBk....",
            ".......kkdkd....",
        } },
        { "Imp1", new[] {
            "................",
            "................",
            "........d.......",
            "........k....d..",
            ".......dbkkkdd..",
            "......kBbbbbBd..",
            ".....kBbBSBbbd..",
            ".....kbbBwsBBk..",
            ".....dbbBsweSk..",
            "....RRBbbBsBsk..",
            "...RrrRBbBsBk...",
            "..k.RRBBBbBBk...",
            ".dk..kBbBBBk....",
            ".ddkddBbkbk.....",
            "..k.dBkd.kBk....",
            ".....d...dkd....",
        } },
        { "Imp2", new[] {
            "................",
            "................",
            ".......d........",
            "......kk...d....",
            "......dbkkdBk...",
            ".....kBbbbbk....",
            "....dbbbBBbbk...",
            "....kbbbssBBe...",
            "....kbbbswSSk...",
            ".....kbbBsSSk...",
            "....RkBbBsSk....",
            "...RrRdBBdBbd...",
            "...RRkbBBbBk....",
            "..kk.kBbBdkd....",
            "..dkkdBkddkk....",
            "..kdkdkd........",
        } },
        { "Imp3", new[] {
            "................",
            "................",
            "......kd........",
            "......kdkkkd....",
            "......kBbbBk....",
            ".....kbbBBbk....",
            ".....kbBssBBk...",
            ".....kbBswdek...",
            "....RBbbSwssk...",
            "...RreBBBsSBk...",
            "...RrdBBBBBBd...",
            "...RRdBBBBdd....",
            ".....kBBBBBk....",
            "..dk.dkkbkBk....",
            "..ddkk..d.k.....",
            "...dd...........",
        } },
        { "Imp4", new[] {
            "................",
            "................",
            "................",
            ".....d..........",
            "....kk...dd.....",
            ".kk.kbkkkBd.kk..",
            "..k.kbbbbbk.kk..",
            "...dBbSBbbk.....",
            "..kwsBSsBBSekkk.",
            ".ewwwswseSwswwk.",
            "..kwwwwwwwwwwk..",
            "kkwwwwwwwwwwwk..",
            "kwsswwwwwssffk..",
            ".kkwwwwwwwwswwk.",
            "...kkkwwkkkkkk..",
            "......kk........",
        } },
    };
    /// <summary>地形块：GroundTop 地面最上层（有草）、GroundFill 地面里层、Wall 墙、Platform 单向板（16×5）、StoneTop、MossWall。</summary>
    public static readonly Dictionary<string, string[]> Tiles = new Dictionary<string, string[]>
    {
        { "GroundTop", new[] {
            "keeeeeeeeeeeeeek",
            "eGGGGGGGGGGGGGGe",
            "eeGeGeeGeGeGGGee",
            "kNeNGNNeNeNeeNNk",
            "eNNNNNNNNNNNNNNe",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "eNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "keeeeeeeeeeeeeek",
        } },
        { "GroundFill", new[] {
            "keNNeNNeeeeeeeek",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNnNNNNNNNNNN",
            "NNNNNNNNnNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "NNNNNNNNNNNNNNNN",
            "keeeeeeeeeeeeeek",
        } },
        { "Wall", new[] {
            "eeeeeeeeeeeeeeee",
            "eSSSSSSSSSSSSSSe",
            "eSSSSSSSSSSSSSSe",
            "eSSSeeSSSSSSeSSe",
            "eeSSSSSSeSSSSSSe",
            "eSSSSSSSSSSSSSSe",
            "eSSSSSSSSSSSSSSe",
            "eeeSSSeSeeSSSSSk",
            "eSSSSeSSSSSSeSSe",
            "eSSSSSSSSSSSSSSe",
            "eSSSSSSSSSSSeSSe",
            "keeeeeeeeeeeeeek",
            "eeSSSSSSeSSSSSSe",
            "eSSSSSSSSSSSSSSe",
            "eSSSSSSSeSSSSSSe",
            "kkeeeeeekkeeeeek",
        } },
        { "Platform", new[] {
            "kkkkkkkkkkkkkkkk",
            "NnnnnnnnnnnnnnnN",
            "NnNNnnNNNnnnnNnN",
            "knnnnnnnnnnnnnnk",
            "xkkkkkkkkkkkkkkx",
        } },
        { "StoneTop", new[] {
            "kkkkkkkkkkkkkkkk",
            "keeeeeeeeeeeeeek",
            "keeeeeeeeeeeeeek",
            "keedkeeeeeekdedk",
            "keeeeeekdedeeeek",
            "keeeeeeeeeeeeeek",
            "keeeeeekeeekekek",
            "keedekekeeeeeedk",
            "keeeeeeekekeeekk",
            "keedeeeedeeeeeek",
            "kekkdeekeeeekeek",
            "kdeeekeedeeekeek",
            "kkeeedeeededeeek",
            "keeeedeeeeeeeeek",
            "keeedeeeeeeeeekk",
            "kkkkkkkkkkkkkkkk",
        } },
        { "MossWall", new[] {
            "eeeeekeeeeeekeek",
            "eSSSSeSSSSSSSSSe",
            "eSSSSSSSSSSSeSSe",
            "eSSSSeSSSSSSeSSe",
            "keSSSSSSeeSSSSSk",
            "eSSSSSSSeSSSSSSe",
            "eSSSSSSSSSSSSSSe",
            "eeeeSeGeeeSSeeSk",
            "eGGSSeGSSSSGeSSe",
            "eSSSSSSSSSSSSSSe",
            "eSSSSeSSSSSSeSSe",
            "keeeeeeeeeeeeeek",
            "eeSGSSSSeSSSSSSe",
            "eSSSSSSSSSSSSSSe",
            "eeSSSSSSeSSSSSSe",
            "kkeeeeeekkeeeeek",
        } },
    };
    public static readonly float[][] BackgroundPalette =
    {
        new[] { 0.38f, 0.337f, 0.467f },
        new[] { 0.286f, 0.294f, 0.404f },
        new[] { 0.278f, 0.267f, 0.361f },
        new[] { 0.255f, 0.267f, 0.365f },
        new[] { 0.247f, 0.259f, 0.357f },
        new[] { 0.251f, 0.255f, 0.345f },
        new[] { 0.239f, 0.255f, 0.349f },
        new[] { 0.227f, 0.231f, 0.314f },
    };
    /// <summary>64×36 背景（每个字符 = BackgroundPalette 下标）。第一行在最上面。</summary>
    public static readonly string[] Background =
    {
        "7777777777777777777777777777777777777777777777777777777777777777",
        "7777777555555555555555555555555555555555555555577777777777777777",
        "7777755555555555555555556765655565556655555555655555777777777777",
        "5555555555555555555555556655555555555556555555555555555557777777",
        "6556555566655666665566666666666666666666666656655556555557577777",
        "6555665444444444444446644444444446444444666444444455555555557777",
        "6524555333444444444344344443444433344434666444444355555562555777",
        "5525224333344444344334444311134433233444666444433455225552255557",
        "5222225434444444444334443101013444333444644344322655222225225557",
        "5522226664664446666444431001001666666666466663222552222525222557",
        "5222225433443344111444430000101333331134444242323552222223222557",
        "5222226434444441000144330100011333310113333555555252222223322557",
        "5222226333443440000133330000100333100001433555555552222223322527",
        "5222234333233430000033320000000333100001443555555552222223112227",
        "5222214333123330000033320000000333100001333567775552222223101225",
        "5222113222223330000033330011101333100001333555555552222223100255",
        "5222013222223330000033310000000333100001333555555552222223100025",
        "5521013333333330000033310000000331100000333257755552222223100015",
        "5510013333333320000033310000000331100000333255535552222223100015",
        "5500013233333320000033310000000311100000333555555555222223100025",
        "5510013333333330010013330000001312100001333355552365522223100122",
        "2210013333333320000013310000001332100001333535552355522223101122",
        "2211113323322331110013310000001332100001333222222255522253101122",
        "2221113313333331111113311101011333100101332233222255522253101122",
        "2221133333333331111133331111111333111111332222232255522253111122",
        "2222233333333331111133331111111343211111333222222345522253111222",
        "2224444444444444444444444444444464444444444444444445525543111222",
        "2226444444444444444444344444444444444444444444444445555433333222",
        "2224343333444444434444444444443443343333343344434345555543443222",
        "5224344444444444434446443444444444443334344444434345525543333222",
        "5224444444444444444444344444444444444444364444434445522543232225",
        "5224444334443444444443344444433334433344444444444445525543242225",
        "5524444446444444664446666666666664444644664444464445525543243525",
        "5554664466666666666666666666666666666666666666666665525743344777",
        "7777667666666666666666666666666666666666666666646665557744667777",
        "7777777776666666666666666666666666666666666666677777777777777777",
    };

    public enum Pose { Idle, RunA, RunB, Jump, Stunned }

    /// <summary>纯逻辑：根据状态挑一帧（跑步 8 帧/秒交替；空中 = 跳；晕 = 晕）。捣蛋者的"晕"帧是变身烟，只在变身那一下用。</summary>
    public static Pose PoseOf(bool grounded, float speedX, bool stunned, float time)
    {
        if (stunned) return Pose.Stunned;
        if (!grounded) return Pose.Jump;
        if (speedX < 0.15f) return Pose.Idle;
        return ((int)(time * 8f)) % 2 == 0 ? Pose.RunA : Pose.RunB;
    }

    /// <summary>纯逻辑：小恶魔的帧——第 5 帧是变身烟（只在变身 / 现形那一下），平时站 / 踮脚 / 跳。</summary>
    public static Pose ImpPose(bool poof, bool grounded, float speedX, float time) => poof ? Pose.Stunned : PoseOf(grounded, speedX, false, time);

    public static string FrameKey(bool hero, Pose p) => (hero ? "Hero" : "Imp") + (int)p;

    public static bool TryColor(char c, out float[] col)
    {
        if (OverworldArt.Palette.TryGetValue(c, out col)) return true;
        return ExtraPalette.TryGetValue(c, out col);
    }

    /// <summary>字符画 → RGBA（从左下角开始，和 Texture2D.SetPixels 一致）。宽 = 每行长度，高 = 行数。</summary>
    public static float[] Rgba(string[] rows)
    {
        if (rows == null || rows.Length == 0) return null;
        int h = rows.Length, w = rows[0].Length; var px = new float[w * h * 4];
        for (int y = 0; y < h; y++) for (int x = 0; x < w; x++)
        {
            char c = rows[h - 1 - y][x]; int i = (y * w + x) * 4;
            if (c == '.' || !TryColor(c, out var col)) continue;
            px[i] = col[0]; px[i + 1] = col[1]; px[i + 2] = col[2]; px[i + 3] = 1f;
        }
        return px;
    }

    public static float[] BackgroundRgba()
    {
        int h = Background.Length, w = Background[0].Length; var px = new float[w * h * 4];
        for (int y = 0; y < h; y++) for (int x = 0; x < w; x++)
        {
            var col = BackgroundPalette[Background[h - 1 - y][x] - '0']; int i = (y * w + x) * 4;
            px[i] = col[0]; px[i + 1] = col[1]; px[i + 2] = col[2]; px[i + 3] = 1f;
        }
        return px;
    }

    /// <summary>纯逻辑：白盒是 1 格 × (sx, sy) 的色块；像素图是正方形 → 取大的那边（夹在 0.6–1 格），扁的东西图里本来就画在底部。</summary>
    public static float FitScale(float sx, float sy)
    {
        float m = sx > sy ? sx : sy; if (m < 0f) m = -m;
        return m < 0.6f ? 0.6f : m > 1f ? 1f : m;
    }

    /// <summary>纯逻辑：图往上挪多少，让图的底边 = 原来色块的底边（扁机关贴地，不会飘在半空或陷进地里）。</summary>
    public static float FitLift(float sy, float scale) => (scale - (sy < 0f ? -sy : sy)) * 0.5f;

    /// <summary>纯逻辑：地形块用哪张图（物体名前缀 → 图块）。墙 / 平台 / 地面最上层有草、下面是土。</summary>
    public static string TileFor(string objectName, bool hasAirAbove)
    {
        string n = objectName ?? "";
        if (n.StartsWith("Wall_")) return "Wall";
        if (n.StartsWith("OneWayPlatform_")) return "Platform";
        if (n.StartsWith("Ground_") || n.StartsWith("Platform_")) return hasAirAbove ? "GroundTop" : "GroundFill";
        return null;
    }
}
