// 自动生成：tools_s242/gen_icons.py（S241 机关图标 + S242 一目了然徽章）。改图标：直接改下面的 16×16 字符画，或者把同名 PNG 放进 Assets/Resources/Step1Icons/<Key>.png 覆盖。
using System.Collections.Generic;

/// <summary>
/// S241：恶作剧房间机关的 16×16 像素图标（用户："图例太密集、看不过来、大脑过载——有没有更形象的图例"）。
/// 第一性原理：认东西靠<b>形状</b>，不靠读字——火苗像火、弹簧像弹簧、香蕉像香蕉；颜色沿用元素原色（形状 + 颜色双编码，色弱也分得清）。
/// 调色板 = OverworldArt.Palette（小镇和房间同一套颜色）；每张图都过 OverworldArt.Audit（≤16 色、深色描边、剪影不太空不太满）。
/// 运行时 Step1PropIcons 只给"没换美术"的白盒机关贴图标（换了主题图的不动）。
/// 参考：Kenney 1-Bit Pack（CC0，16×16 一眼可读的图标做法）https://kenney.nl/assets/1-bit-pack ；色弱友好的形状 + 颜色双编码 https://colorblindgames.com/2023/04/19/universal-colorblind-code/
/// </summary>
public static class Step1Icons
{
    public const int Size = OverworldArt.Size;

    /// <summary>元素主题键（= 物体名前缀）→ 图标名。香蕉皮 / 道具箱 / 箱子 / 大炮和小镇共用图标。</summary>
    public static readonly Dictionary<string, string> ByKey = new Dictionary<string, string>
    {
        { "FireTrap", "FireTrap" },
        { "ControllableBlocker", "ControllableBlocker" },
        { "CollapsingPlatform", "CollapsingPlatform" },
        { "SpringPad", "SpringPad" },
        { "CrackFloor", "CrackFloor" },
        { "IronCage", "IronCage" },
        { "SnareTrap", "SnareTrap" },
        { "OilBarrel", "OilBarrel" },
        { "Tripwire", "Tripwire" },
        { "Vent", "Vent" },
        { "CrackedWall", "CrackedWall" },
        { "Bush", "Bush" },
        { "OneWayDoor", "OneWayDoor" },
        { "PoisonPool", "PoisonPool" },
        { "Glue", "Glue" },
        { "RoomLamp", "RoomLamp" },
        { "SpikeTrap", "SpikeTrap" },
        { "Cannon", "Cannon" },
        { "PickupSpot", "PickupSpot" },
        { "Crate", "Crate" },
        { "GrassGround", "GrassGround" },
        { "BadgeLoot", "BadgeLoot" },
        { "BadgeExit", "BadgeExit" },
        { "BadgeQuestion", "BadgeQuestion" },
        { "BadgeAlert", "BadgeAlert" },
        { "BadgeEye", "BadgeEye" },
        { "BadgeStar", "BadgeStar" },
        { "BadgeAmbush", "BadgeAmbush" },
        { "BadgeHide", "BadgeHide" },
        { "BananaPeel", "BananaPeel" },
    };

    public static readonly Dictionary<string, string[]> Icons = new Dictionary<string, string[]>
    {
        { "FireTrap", new[] {
            "................",
            "........k.......",
            ".......krk......",
            "......krrrk.....",
            "......krrrk.....",
            "....k.krrrrk....",
            "...krkrrrrrrk...",
            "..krrrroorrrrk..",
            "..krrroooorrrk..",
            "..krroooooorrk..",
            "..krroooooorrk..",
            "..krrooyyoorrk..",
            "..krrooyyoorrk..",
            "...kkrroorrkk...",
            ".....kkrrkk.....",
            ".......kk.......",
        } },
        { "ControllableBlocker", new[] {
            "................",
            "................",
            "................",
            ".kkkkkkkkkkkkkk.",
            "kwwwrrwwrrwwrrwk",
            "kwwrrwwrrwwrrwwk",
            "kwwrrwwrrwwrrwwk",
            "kwrrwwrrwwrrwwrk",
            "krrwwrrwwrrwwrrk",
            "kwwwwwwwwwwwwwwk",
            ".kkSSkkkkkkSSkk.",
            "..kSSk....kSSk..",
            "..kSSk....kSSk..",
            ".kkSSkkkkkkSSkk.",
            "kSSSSSSSSSSSSSSk",
            ".kkkkkkkkkkkkkk.",
        } },
        { "CollapsingPlatform", new[] {
            "................",
            "................",
            ".kkkkk....kkkkk.",
            "knnnnnk..knnnnnk",
            "knnnnnk..knnnnnk",
            "kNNNNNk..kNNNNNk",
            ".kkkkknkk.kkkkk.",
            ".....knnnk......",
            "......knnk......",
            ".......kk.......",
            "......kwwk......",
            "......kwwk......",
            ".....kwwwk......",
            ".....kwwwk......",
            "......kwk.......",
            ".......k........",
        } },
        { "SpringPad", new[] {
            ".......kk.......",
            "...kkkkwwkkkk...",
            "..kggggggggggk..",
            "..kggggggggggk..",
            "..kggggggggggk..",
            "...kkssskkkkk...",
            ".....kkkksssk...",
            "....kssskkkk....",
            ".....kkkksssk...",
            "....kssskkkk....",
            ".....kkkksssk...",
            "..kkkssskkkkkk..",
            ".kGGGGGGGGGGGGk.",
            ".kGGGGGGGGGGGGk.",
            ".kGGGGGGGGGGGGk.",
            "..kkkkkkkkkkkk..",
        } },
        { "CrackFloor", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            ".kkkkkkkkkkkkkk.",
            "kNNNNNNNNNNNNNNk",
            "kNNNkNNNNNNNNNNk",
            "knnnnknnnnnnnnnk",
            "knnnnnknnkkknnnk",
            "knnnnnnkkknnknnk",
            "knnnnnnknnnnknnk",
            "knnnnnknnnnnnknk",
            "knnnnnknnnnnnnnk",
            ".kkkkk.kkkkkkkk.",
            "................",
        } },
        { "IronCage", new[] {
            ".......kk.......",
            "......kSSk......",
            "..kkkkkSSkkkkk..",
            ".kSSSSSSSSSSSSk.",
            ".kSSSSSSSSSSSSk.",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            "..kskkskkskksk..",
            ".kSSSSSSSSSSSSk.",
            "..kkkkkkkkkkkk..",
        } },
        { "SnareTrap", new[] {
            ".......kk.......",
            "......knnk......",
            "......knnk......",
            "......knnk......",
            "......knnk......",
            "......knnkk.....",
            ".....knnnnnk....",
            "....knnnnnnnk...",
            "...knnnkkknnnk..",
            "...knnk...knnk..",
            "...knnk...knnk..",
            "...knnk...knnk..",
            "...knnnkkknnnk..",
            "....knnnnnnnk...",
            ".....knnnnnk....",
            "......kkkkk.....",
        } },
        { "OilBarrel", new[] {
            "................",
            "....kkkkkkkk....",
            "...krrrrrrrrk...",
            "...krrrrrrrrk...",
            "...krrrrrrrrkk..",
            "..kRRRRRRRRRRRk.",
            "..krrrrrrrrrrk..",
            "..krrrryyrrrrk..",
            "..krrryyyyrrrk..",
            "..krrrryyrrrrk..",
            "..krrrrrrrrrrk..",
            "..kRRRRRRRRRRRk.",
            "...krrrrrrrrkk..",
            "...krrrrrrrrk...",
            "....kkkkkkkk....",
            "................",
        } },
        { "Tripwire", new[] {
            "................",
            "................",
            "................",
            "..kk........kk..",
            ".knnk......knnk.",
            ".knnk......knnk.",
            ".knnk......knnk.",
            ".knnk......knnk.",
            ".knnk.kkkk.knnk.",
            ".knnkkwwwwkknnk.",
            ".knwwwwwwwwwwnk.",
            ".knnkkkkkkkknnk.",
            ".knnk......knnk.",
            ".knnkkkkkkkknnk.",
            "kNNNNNNNNNNNNNNk",
            ".kkkkkkkkkkkkkk.",
        } },
        { "Vent", new[] {
            "................",
            "..kkkkkkkkkkkk..",
            ".kSSSSSSSSSSSSk.",
            ".kSkkkkkkkkkkSk.",
            ".kSssssssssssSk.",
            ".kSssssssssssSk.",
            ".kSkkkkkkkkkkSk.",
            ".kSssssssssssSk.",
            ".kSssssssssssSk.",
            ".kSkkkkkkkkkkSk.",
            ".kSssssssssssSk.",
            ".kSssssssssssSk.",
            ".kSkkkkkkkkkkSk.",
            ".kSSSSSSSSSSSSk.",
            "..kkkkkcckkkkk..",
            ".......kk.......",
        } },
        { "CrackedWall", new[] {
            "................",
            "...kkkkkkkkkk...",
            "..kSSSSsSSSSSk..",
            "..kSSSksSSSSSk..",
            "..kSSSSkSSSSSk..",
            "..ksssskkssssk..",
            "..kSSsSSkSsSSk..",
            "..kSSsSSSksSSk..",
            "..kSSsSSkSsSSk..",
            "..kssssskssssk..",
            "..kSSSSkSSSSSk..",
            "..kSSSSskSSSSk..",
            "..kSSSSsSkSSSk..",
            "..kSSSSSSSkSSk..",
            "...kkkkkkk.kk...",
            "................",
        } },
        { "Bush", new[] {
            "................",
            "................",
            ".......kkk......",
            ".....kkgggkk....",
            "....kgggggggk...",
            "....kggyggggk...",
            "...kggyyyggggk..",
            "..kGgggygggggGk.",
            ".kGGggggggyggGGk",
            ".kGGGggggyyyGGGk",
            ".kGGGgggggygGGGk",
            ".kGGGGGgggGGGGGk",
            ".kGGGGGGGGGGGGGk",
            ".kGGGGGGGGGGGGk.",
            ".kGGGGGGGGGGGGk.",
            "..kkkkkkkkkkkk..",
        } },
        { "OneWayDoor", new[] {
            "...kkkkkkkkkk...",
            "..knnnnnnnnnnk..",
            "..knNNNNNNNNnk..",
            "..knNNNNNNNNnk..",
            "..knNNNNNNNNnk..",
            "..kyNNNNNNNNnk..",
            ".kyyNNNNNNNNnk..",
            "kyyyNNNNNyyNnk..",
            "kyyyNNNNNyyNnk..",
            ".kyyNNNNNNNNnk..",
            "..kyNNNNNNNNnk..",
            "..knNNNNNNNNnk..",
            "..knNNNNNNNNnk..",
            "..knNNNNNNNNnk..",
            "..knnnnnnnnnnk..",
            "...kkkkkkkkkk...",
        } },
        { "PoisonPool", new[] {
            "................",
            "...........k....",
            "..........kpk...",
            ".......kkkpppk..",
            "......kpppkpk...",
            "......kpppkk....",
            "......kpppk.....",
            "...kkkkkkkkkk...",
            "..kppppppppppk..",
            ".kppppwpppppppk.",
            "kppppwwwppwppppk",
            ".kppppwppwwwppk.",
            ".kppppppppwpppk.",
            "..kppppppppppk..",
            "...kkkkkkkkkk...",
            "................",
        } },
        { "Glue", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "...kkkkkkkkkk...",
            "..kyyyyyyyyyyk..",
            ".kyyyyywyyyyyyk.",
            "kyyyyywwwyyyyyyk",
            ".kyyyyywyyyyyyk.",
            ".kyyyyyyyyyyyyk.",
            "..kyyyyyyyyyyk..",
            "...kkYYkkkYkk...",
            "....kYYk.kYk....",
            "....kkkk..k.....",
        } },
        { "RoomLamp", new[] {
            "................",
            "....kkkkkkkk....",
            "...kyyyyyyyyk...",
            "....kywwwwyk....",
            "....kywwwwyk....",
            "....kyyyyyyk....",
            ".....kyyyyk.....",
            "......kkkk......",
            "......kSSk......",
            "......kSSk......",
            "......kSSk......",
            "......kSSk......",
            "......kSSk......",
            "....kkkSSkkk....",
            "...kSSSSSSSSk...",
            "....kkkkkkkk....",
        } },
        { "SpikeTrap", new[] {
            "................",
            "................",
            "................",
            "................",
            "................",
            "..kk...kk...kk..",
            ".kssk.kssk.kssk.",
            ".kssk.kssk.kssk.",
            ".kssk.kssk.kssk.",
            ".kssk.kssk.kssk.",
            ".kssk.kssk.kssk.",
            "kssssksssskssssk",
            "kssssksssskssssk",
            "kSSSSSSSSSSSSSSk",
            "kSSSSSSSSSSSSSSk",
            ".kkkkkkkkkkkkkk.",
        } },
        { "Cannon", new[] {
            "................",
            "................",
            "............kk..",
            ".........kkkSSk.",
            ".....kkkkSSSSSk.",
            "...kkSSSSSSSSSk.",
            "..kSSSSSSSSSSSSk",
            "..kSSSSSSSSSSSSk",
            "..kSNNNSSSSSSkk.",
            "..kNNNNNSSkkk...",
            ".kNNNnNNNk......",
            ".kNNnnnNNk......",
            ".kNNNnNNNk......",
            ".kkNNNNNkkk.....",
            "kNNNNNNNNNNk....",
            ".kkkkkkkkkk.....",
        } },
        { "PickupSpot", new[] {
            "................",
            "..kkkkkkkkkkkk..",
            ".kyyyyyyyyyyyyk.",
            ".kyYYYYYYYYYYyk.",
            ".kyYYYwwwwYYYyk.",
            ".kyYYYYYYYwYYyk.",
            ".kyYYYYYYYwYYyk.",
            ".kyYYYYYYwYYYyk.",
            ".kyYYYYYwYYYYyk.",
            ".kyYYYYYwYYYYyk.",
            ".kyYYYYYYYYYYyk.",
            ".kyYYYYYwYYYYyk.",
            ".kyYYYYYwYYYYyk.",
            ".kyyyyyyyyyyyyk.",
            "..kkkkkkkkkkkk..",
            "................",
        } },
        { "Crate", new[] {
            "................",
            "..kkkkkkkkkkkk..",
            ".kNNNNNNNNNNNNk.",
            ".kNNNNNNNNNNNNk.",
            ".kNNNnnnnnnnNNk.",
            ".kNNnNnnnnnnNNk.",
            ".kNNnnNnnnnnNNk.",
            ".kNNnnnNnnnnNNk.",
            ".kNNnnnnNnnnNNk.",
            ".kNNnnnnnNnnNNk.",
            ".kNNnnnnnnNnNNk.",
            ".kNNnnnnnnnNNNk.",
            ".kNNNNNNNNNNNNk.",
            ".kNNNNNNNNNNNNk.",
            "..kkkkkkkkkkkk..",
            "................",
        } },
        { "GrassGround", new[] {
            "................",
            "................",
            "................",
            "k..k..k..k..k..k",
            "kkkGkkGkkGkkGkkk",
            "kkkGkkGkkGkkGkkk",
            "kggGggGggGggGggk",
            "kggggggggggggggk",
            "kggggggggggggggk",
            "kggggggggggggggk",
            "knnnnnnnnnnnnnnk",
            "knnnnnnnnnnnnnnk",
            "knnnnnnnnnnnnnnk",
            "knnnnnnnnnnnnnnk",
            "knnnnnnnnnnnnnnk",
            "kkkkkkkkkkkkkkkk",
        } },
        { "BadgeLoot", new[] {
            ".....kkkkkk.....",
            "...kkYYYYYYkk...",
            "..kYYYYYYYYYYk..",
            ".kYYYYYyYYYYYYk.",
            ".kYYYYyyyYYYYYk.",
            "kYYYYyyyyyYYYYYk",
            "kYYNNNNNNNNNNYYk",
            "kYYNNNNNNNNNNYYk",
            "kYYnnnnyynnnYYYk",
            "kYYnnnnyynnnYYYk",
            "kYYnnnnyynnnYYYk",
            ".kYnnnnnnnnnYYk.",
            ".kYYYYYYYYYYYYk.",
            "..kYYYYYYYYYYk..",
            "...kkYYYYYYkk...",
            ".....kkkkkk.....",
        } },
        { "BadgeExit", new[] {
            ".....kkkkkk.....",
            "...kkGGGGGGkk...",
            "..kGGGGGGGGGGk..",
            ".kGGGNNNNNNGGGk.",
            ".kGGGNkkkkNGGGk.",
            "kGGGGwkkkkNGGGGk",
            "kGGGwwkkkkNGGGGk",
            "kGGwwwkkkkNGGGGk",
            "kGGwwwkkkkNGGGGk",
            "kGGGwwkkkkNGGGGk",
            "kGGGGwkkkkNGGGGk",
            ".kGGGNkkkkNGGGk.",
            ".kGGGNkkkkNGGGk.",
            "..kGGGGGGGGGGk..",
            "...kkGGGGGGkk...",
            ".....kkkkkk.....",
        } },
        { "BadgeQuestion", new[] {
            ".....kkkkkk.....",
            "...kkyyyyyykk...",
            "..kyyyyyyyyyyk..",
            ".kyyyykkkkyyyyk.",
            ".kyyyykyyykyyyk.",
            "kyyyyyyyyykyyyyk",
            "kyyyyyyyykkyyyyk",
            "kyyyyyyykyyyyyyk",
            "kyyyyyykyyyyyyyk",
            "kyyyyyykyyyyyyyk",
            "kyyyyyyyyyyyyyyk",
            ".kyyyyykkyyyyyk.",
            ".kyyyyykkyyyyyk.",
            "..kyyyyyyyyyyk..",
            "...kkyyyyyykk...",
            ".....kkkkkk.....",
        } },
        { "BadgeAlert", new[] {
            ".....kkkkkk.....",
            "...kkrrrrrrkk...",
            "..krrrrrrrrrrk..",
            ".krrrrrwwrrrrrk.",
            ".krrrrrwwrrrrrk.",
            "krrrrrrwwrrrrrrk",
            "krrrrrrwwrrrrrrk",
            "krrrrrrwwrrrrrrk",
            "krrrrrrwwrrrrrrk",
            "krrrrrrwwrrrrrrk",
            "krrrrrrrrrrrrrrk",
            ".krrrrrwwrrrrrk.",
            ".krrrrrwwrrrrrk.",
            "..krrrrrrrrrrk..",
            "...kkrrrrrrkk...",
            ".....kkkkkk.....",
        } },
        { "BadgeEye", new[] {
            ".....kkkkkk.....",
            "...kkbbbbbbkk...",
            "..kbbbbbbbbbbk..",
            ".kbbbbbbbbbbbbk.",
            ".kbbbbbwbbbbbbk.",
            "kbbbbwwwwwbbbbbk",
            "kbbbwwwBBwwbbbbk",
            "kbwwwwBkkBwwwbbk",
            "kbbbwwBkkBwbbbbk",
            "kbbbbwwBBwbbbbbk",
            "kbbbbbbwbbbbbbbk",
            ".kbbbbbbbbbbbbk.",
            ".kbbbbbbbbbbbbk.",
            "..kbbbbbbbbbbk..",
            "...kkbbbbbbkk...",
            ".....kkkkkk.....",
        } },
        { "BadgeStar", new[] {
            ".....kkkkkk.....",
            "...kkppppppkk...",
            "..kppppypppppk..",
            ".kpppppyppppppk.",
            ".kpppppyppppppk.",
            "kpppppyyyppppppk",
            "kpyyyyyyyyyyyppk",
            "kppyyyyyyyyypppk",
            "kpppyyyyyyyppppk",
            "kppppyyyyypppppk",
            "kppppyypyypppppk",
            ".kppyypppyypppk.",
            ".kppypppppypppk.",
            "..kppppppppppk..",
            "...kkppppppkk...",
            ".....kkkkkk.....",
        } },
        { "BadgeAmbush", new[] {
            ".....kkkkkk.....",
            "...kkrrrrrrkk...",
            "..krrrrrrrrrrk..",
            ".krrrrrwwrrrrrk.",
            ".krrrwwwwwwrrrk.",
            "krrrwwrrrrwwrrrk",
            "krrrwrrrrrrwrrrk",
            "krrwwrrwwrrwwrrk",
            "krrwwrrwwrrwwrrk",
            "krrrwrrrrrrwrrrk",
            "krrrwwrrrrwwrrrk",
            ".krrrwwwwwwrrrk.",
            ".krrrrrwwrrrrrk.",
            "..krrrrrrrrrrk..",
            "...kkrrrrrrkk...",
            ".....kkkkkk.....",
        } },
        { "BadgeHide", new[] {
            ".....kkkkkk.....",
            "...kkbbbbbbkk...",
            "..kbbbbbbbbbbk..",
            ".kbbbbggggbbbbk.",
            ".kbbgggggggbbbk.",
            "kbbbbgyyggggbbbk",
            "kbbbbggggggbbbbk",
            "kbbGGggggggGGbbk",
            "kbGGGggggyyGGGbk",
            "kbGGGGggggGGGGbk",
            "kbGGGGGGGGGGGGbk",
            ".kGGGGGGGGGGGGk.",
            ".kGGGGGGGGGGGGk.",
            "..kbbbbbbbbbbk..",
            "...kkbbbbbbkk...",
            ".....kkkkkk.....",
        } },
    };

    /// <summary>这个元素有没有图标（房间自己的 → 小镇的）。</summary>
    public static bool Has(string key) => key != null && ByKey.TryGetValue(key, out var n) && (Icons.ContainsKey(n) || OverworldArt.Icons.ContainsKey(n));

    /// <summary>RGBA 像素（从左下角开始，和 Texture2D.SetPixels 顺序一致）。没有 = null。</summary>
    public static float[] Pixels(string key)
    {
        if (key == null || !ByKey.TryGetValue(key, out var name)) return null;
        if (!Icons.TryGetValue(name, out var rows)) return OverworldArt.Pixels(name);
        var px = new float[Size * Size * 4];
        for (int y = 0; y < Size; y++) for (int x = 0; x < Size; x++)
        {
            char c = rows[Size - 1 - y][x]; int i = (y * Size + x) * 4;
            if (c == '.' || !OverworldArt.Palette.TryGetValue(c, out var col)) continue;
            px[i] = col[0]; px[i + 1] = col[1]; px[i + 2] = col[2]; px[i + 3] = 1f;
        }
        return px;
    }
}
